---
# just to ensure ansible colections ensured
# usage: 'ansible-galaxy collection install -r collections/requirements.yml' 
collections:
  - name: community.general
  - name: community.libvirt
  - name: community.vmware
  - name: community.postgresql
