---
# virtualisation parameters
vm:
  name: "db02-local"
  hostname: "db02-local"
  mac: "52:54:00:ab:cd:12"
  vcpus: 2
  memory_mb: 4096
  os_disk_gb: 10
  data_disk_gb: 20
  ip_cidr: "192.168.122.112/24"
  gateway: "192.168.122.1"
  dns_servers: ["192.168.122.1"]
  password: "Rocky_Balb0a" # should be in the vault
  lvm_device: "/dev/vdb"

#os_config:
#no specific values per machine, all in group_vars
#


# postgresql specific values    
postgresql_cluster_name: "db02-replica"
postgresql_port: 5432

# postgresql replication variables
replication_role: standby
replication_primary_host: "192.168.122.111"  # db01-local
replication_primary_port: 5432
replication_slot: "slot_db02"
